import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";

export default function Home({ exploreData, cardsData }) {
  return (
    <div className="">
      <Head>
        <title>AirBnb Build</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />

      {/* Banner */}
      <Banner />

      <main className="max-w-6xl mx-auto px-8 sm:px-16">
        <section className="mt-10 md:mt-16">
          <h2 className="text-4xl font-semibold mb-5 md:mb-10 ">
            Explore Nearby
          </h2>

          {/* Small cards*/}
          <div className="grid grid-cols-1 gap-4 md:gap-8 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            {exploreData.map((item) => (
              <SmallCard
                key={item.img}
                img={item.img}
                location={item.location}
                distance={item.distance}
              />
            ))}
          </div>
        </section>
        <section className="mt-10 md:mt-16">
          <h2 className="text-4xl font-semibold mb-5 md:mb-10">
            Live Anywhere
          </h2>
          {/* Medium Cards*/}
          <div className="flex gap-3 overflow-scroll  p-3">
            {cardsData.map((item) => (
              <MediumCard key={item.img} img={item.img} title={item.title} />
            ))}
          </div>
        </section>

        <LargeCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb"
          buttonText="Get Inspired"
        />
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  let exploreData, cardsData;

  try {
    const response = await fetch(`https://links.papareact.com/pyp`);
    exploreData = await response.json();
  } catch (error) {
    console.error(error);
  }

  try {
    const response = await fetch(`https://links.papareact.com/zp1`);
    cardsData = await response.json();
  } catch (error) {
    console.error(error);
  }

  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
